language: csharp
solution: digos-ambassador.sln
os:
  - linux
  - osx
mono: latest
dotnet: 2.1.3
before_install:
    - git config --global url."https://github.com/".insteadOf "git@github.com:"
    - dotnet restore
script:
    - msbuild /p:Configuration=Release digos-ambassador.sln